version: '3'

services:
    db:
        image: 'postgres:11'
        restart: always
        ports:
            - "5555:5432"
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=go_buffalo_api_development
