package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"go_buffalo_api/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Author)
// DB Table: Plural (authors)
// Resource: Plural (Authors)
// Path: Plural (/authors)
// View Template Folder: Plural (/templates/authors/)

// AuthorsResource is the resource for the Author model
type AuthorsResource struct {
	buffalo.Resource
}

// List gets all Authors. This function is mapped to the path
// GET /authors
func (v AuthorsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	authors := &models.Authors{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Authors from the DB
	if err := q.All(authors); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("authors", authors)
		return c.Render(http.StatusOK, r.HTML("authors/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(authors))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(authors))
	}).Respond(c)
}

// Show gets the data for one Author. This function is mapped to
// the path GET /authors/{author_id}
func (v AuthorsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Author
	author := &models.Author{}

	// To find the Author the parameter author_id is used.
	if err := tx.Find(author, c.Param("author_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("author", author)

		return c.Render(http.StatusOK, r.HTML("authors/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(author))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(author))
	}).Respond(c)
}

// Create adds a Author to the DB. This function is mapped to the
// path POST /authors
func (v AuthorsResource) Create(c buffalo.Context) error {
	// Allocate an empty Author
	author := &models.Author{}

	// Bind author to the html form elements
	if err := c.Bind(author); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(author)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("author", author)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("authors/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "author.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/authors/%v", author.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(author))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(author))
	}).Respond(c)
}

// Update changes a Author in the DB. This function is mapped to
// the path PUT /authors/{author_id}
func (v AuthorsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Author
	author := &models.Author{}

	if err := tx.Find(author, c.Param("author_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Author to the html form elements
	if err := c.Bind(author); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(author)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("author", author)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("authors/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "author.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/authors/%v", author.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(author))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(author))
	}).Respond(c)
}

// Destroy deletes a Author from the DB. This function is mapped
// to the path DELETE /authors/{author_id}
func (v AuthorsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Author
	author := &models.Author{}

	// To find the Author the parameter author_id is used.
	if err := tx.Find(author, c.Param("author_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(author); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "author.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/authors")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(author))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(author))
	}).Respond(c)
}
